### ISSUE TITLE
Terminology needs to be expanded in the Spec

### ISSUE THREAD

**Issue by mkhraisha** [w3c-ccg/traceability-interop#27] opened 2021-10-05 18:19 UTC
The terminology section of the spec needs to be expanded on, as it is currently pretty barren.

**Comment by OR13** [comment] 2021-11-16 19:15
Example of how to cite terms defined in other specs: https://github.com/decentralized-identity/JWS-Test-Suite/blob/main/data/index.html#L154

**Comment by nissimsan** [comment] 2022-01-11 18:53
@mkhraisha to link to trace-vocab, adding missing parts. 
(Not for next week though)

**Comment by OR13** [comment] 2022-02-08 19:16
seems a bit of a dupe of the trace-vocab related item.

seems like we need to define security terms related to interop profile.

**Closed** 2022-02-22 19:27 UTC
