### ISSUE TITLE
Test case should be added for oauth presentation exchange

### ISSUE THREAD

**Issue by nissimsan** [w3c-ccg/traceability-interop#211] opened 2022-05-03 18:26 UTC
An "oauth authenticated presentation exchange" test case should be added to test for the POST /presentations which was added in https://github.com/w3c-ccg/traceability-interop/pull/206.

**Comment by OR13** [comment] 2022-05-17 18:18
This is a dupe of https://github.com/w3c-ccg/traceability-interop/issues/95

**Closed by OR13** 2022-05-17 18:18 UTC
